### ISSUE TITLE
Se ne morem prijaviti na bazo

### ISSUE THREAD

**Issue by andrejbauer** [campovski/zbiratelj#15]
Ok, zdja lahko prevedem program, ampak hoče še lokalno mysql bazo. Nisem čisto prepričan, da si želim namestiti Mysql na svoj dekstop. A se lahko bodisi zmenimo za live demo ali pa da mi dasta dostop do neke mysql baze nekje?

**Comment by campovski** [comment]
Mislim, da je ta issue odpravljen.
